name: Appium TestNG Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          Distribution : 'temurin'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          npm install -g appium

      - name: Install Android SDK
        run: |
          # Install necessary dependencies for Android SDK
          sudo apt-get install -y wget unzip lib32stdc++6 lib32z1

          # Download the Android SDK Command Line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip

          # Unzip the downloaded tools
          sudo unzip commandlinetools-linux-6858069_latest.zip -d /usr/local/android-sdk

          # Set environment variables
          echo "export ANDROID_SDK_ROOT=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:/usr/local/android-sdk/cmdline-tools/bin" >> $GITHUB_ENV

          # Accept licenses (run sdkmanager command)
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "tools" "build-tools;29.0.2" "android-29" # Install required components

      - name: Set up Android Emulator (optional)
        run: |
          # You can set up an Android Emulator if needed.
          echo "y" | android update sdk --no-ui --filter tools,platform-tools,build-tools-29.0.2,android-29
          echo "y" | android create avd --force --name test --target android-29 --abi x86_64
          emulator -avd test -no-window &

      - name: Start Appium Server
        run: |
          appium &  # Start Appium server in the background
          sleep 5  # Wait for the server to fully start

      - name: Run TestNG Appium Tests
        run: |
          mvn clean test  # Run Maven tests (TestNG)

      - name: Stop Appium Server
        run: |
          pkill -f appium  # Kill Appium process if it's still running
