name: Appium TestNG Tests

on:
  push:
    branches:
      - main  # Trigger on push to main (change if needed)
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the main branch

jobs:
  appium-tests:
    runs-on: macos-latest  # You can also use macos-latest depending on your setup

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Java (Required for Appium and TestNG)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      # Step 3: Install dependencies (Node.js, Appium, etc.)
      - name: set appium
        run: |
          npm install -g appium@v2.15 # Install Appium globally
          appium -v
          appium &>/dev/null &
          

      - name: run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: mvn clean test -Pandroid
      
     
