name: Appium TestNG Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  appium-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17 (or 11, depending on your preference)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Install Node.js and Appium globally
      - name: Setup Appium
        run: |
          npm install -g appium@v2.15
          appium -v
          appium &>/dev/null &
          sleep 5

     

      # Step 5: Set up Android Emulator using the reactivecircus action
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29  # Adjust to the API level you need
          script: |
            # Ensure the emulator is ready before starting the tests
            adb devices
            sleep 10  # Additional time for the emulator to initialize if needed

      # Step 6: Run Appium Tests with Maven (using the android profile)
      - name: Run Appium Tests
        run: mvn clean test 

      # Step 7: Terminate Emulator after the tests are done
      - name: Terminate Emulator
        run: |
          adb devices
          adb emu kill || echo "Emulator not running"
