name: Appium TestNG Tests

on:
  push:
    branches:
      - main  # Trigger on push to main (change if needed)
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the main branch

jobs:
  appium-tests:
    runs-on: macos-latest  # You can also use macos-latest depending on your setup

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 (Required for Appium and TestNG)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 4: Install Appium globally
      - name: Install Appium
        run: |
          npm install -g appium@v2.15
          appium -v
          appium &>/dev/null &

      # Step 5: Install Android SDK
      - name: Install Android SDK
        run: |
          # Download and extract the command line tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-mac-8512546_latest.zip -o cmdline-tools.zip
          mkdir -p $HOME/Android/cmdline-tools
          unzip cmdline-tools.zip -d $HOME/Android/cmdline-tools/
          rm cmdline-tools.zip
          
          # Accept licenses and install required components
          yes | $HOME/Android/cmdline-tools/bin/sdkmanager --licenses
          $HOME/Android/cmdline-tools/bin/sdkmanager --update
          $HOME/Android/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-29" "system-images;android-29;google_apis;x86_64"

      # Step 6: Set the ANDROID_SDK_ROOT environment variable
      - name: Set ANDROID_SDK_ROOT
        run: echo "ANDROID_SDK_ROOT=$HOME/Android" >> $GITHUB_ENV

      # Step 7: Set up Android Emulator
      - name: Set up Android Emulator
        run: |
          echo "no" | $HOME/Android/cmdline-tools/bin/avdmanager create avd --name test-emulator --package "system-images;android-29;google_apis;x86_64"
          $HOME/Android/emulator/emulator -avd test-emulator -no-window -no-audio -gpu swiftshader_indirect &

      # Step 8: Wait for Emulator to boot
      - name: Wait for Emulator to boot
        run: |
          adb wait-for-device

      # Step 9: Run Appium Android Tests using Maven
      - name: Run Appium Android Tests
        run: mvn clean test -Pandroid

      # Debug Step (Optional): Check SDK installation and environment
      - name: Debug SDK path
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          echo "SDK installed at: $HOME/Android/cmdline-tools/bin/sdkmanager"
          ls -l $HOME/Android
          ls -l $HOME/Android/cmdline-tools
